baseURL = "https://angelahollings.com"
title = "Angela Hollings"
theme = "chunky-poster"
copyright = "Copyright Â© 2019 Angela Hollings | Icon made by SmallLikeArt from www.flaticon.com"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0
	[[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "https://www.notion.so/angelas/Angela-Hollings-130fcff2af0343ff8d9e21f282b41934"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Angela Hollings"
  description = "Finding evidence based and actionable resources to promote learning and growth"
  homepageImage = "/images/homepage.png"
  share = true

  [params.social]
    rss = true
    email = "ange.hollings@gmail.com"
    twitter = "https://twitter.com/AngelaLHollings"
    linkedin = "https://www.linkedin.com/in/angela-hollings/"
    github = "https://github.com/AngelaLH"

  [params.prismJS]
    enable = true
    theme = ""

[markup]
  [markup.highlight]
    codeFences = false

[services]

  [services.twitter]
    disableInlineCSS = true
